/**
 * Database Row Types
 * 
 * These interfaces represent the actual structure of rows returned from
 * Supabase PostgreSQL database. They are separate from domain types (Profile, Goal)
 * to maintain a clear boundary between DB schema and app logic.
 * 
 * Usage:
 * - Use these types for database query results
 * - Map to domain types using convertDbProfileToProfile() etc.
 * - This prevents runtime errors from unexpected DB column names
 */

/**
 * Database achievements structure (JSON type in PostgreSQL)
 */
export interface DbAchievements {
  stars: number;
  streak: number;
  recitations: number;
  goalsCompleted: number;
}

/**
 * Profile row in PostgreSQL
 * Maps directly to public.profiles table schema
 */
export interface DbProfileRow {
  // Primary key and metadata
  id: string; // UUID, generated by Supabase
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp

  // Identity
  name: string;
  email: string | null; // Nullable - only parent profiles require email
  type: 'parent' | 'child';

  // Relationships
  parent_id: string | null; // UUID, null for parents; FK to profiles.id

  // Display
  avatar: string | null; // URL or avatar key

  // Profile details
  age: number | null;
  arabic_proficiency: boolean | null;
  arabic_accent: string | null;
  tajweed_level: 'beginner' | 'intermediate' | 'advanced' | null;

  // Learning state
  current_goal: string | null; // Goal name or null
  goals_count: number; // Denormalized count (also in goals table)
  streak: number; // Days of consecutive practice

  // Achievements (JSON)
  achievements: DbAchievements;
}

/**
 * Goal row in PostgreSQL
 * Maps directly to public.goals table schema
 */
export interface DbGoalRow {
  // Primary key and metadata
  id: string; // UUID, auto-generated
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp

  // Relationships
  profile_id: string; // UUID, FK to profiles.id (enforced by RLS)

  // Goal definition
  goal_id: string; // Reference to goal configuration (e.g., 'juz_1', 'surah_fatiha')
  name: string; // Human-readable name (e.g., 'Juz 1', 'Surah Al-Fatiha')

  // Progress state
  status: 'in-progress' | 'completed' | 'paused';
  completed_surahs: number;
  total_surahs: number;

  // Learning configuration
  phase_size: number; // How many verses per phase (1-30, typically 5-10)
  current_unit_id: string | null; // Current unit being studied (Surah number, etc.)

  // Completion
  completion_date: string | null; // ISO timestamp when goal was completed
}

/**
 * Validator schemas for DB rows
 * These ensure type safety at runtime
 */
import { z } from 'zod';

export const DbAchievementsSchema = z.object({
  stars: z.number().int().nonnegative(),
  streak: z.number().int().nonnegative(),
  recitations: z.number().int().nonnegative(),
  goalsCompleted: z.number().int().nonnegative(),
});

export const DbProfileRowSchema = z.object({
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string(),
  email: z.string().email().nullable(),
  type: z.enum(['parent', 'child']),
  parent_id: z.string().uuid().nullable(),
  avatar: z.string().nullable(),
  age: z.number().int().positive().nullable(),
  arabic_proficiency: z.boolean().nullable(),
  arabic_accent: z.string().nullable(),
  tajweed_level: z.enum(['beginner', 'intermediate', 'advanced']).nullable(),
  current_goal: z.string().nullable(),
  goals_count: z.number().int().nonnegative(),
  streak: z.number().int().nonnegative(),
  achievements: DbAchievementsSchema,
});

export const DbGoalRowSchema = z.object({
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  profile_id: z.string().uuid(),
  goal_id: z.string(),
  name: z.string(),
  status: z.enum(['in-progress', 'completed', 'paused']),
  completed_surahs: z.number().int().nonnegative(),
  total_surahs: z.number().int().positive(),
  phase_size: z.number().int().positive(),
  current_unit_id: z.string().nullable(),
  completion_date: z.string().datetime().nullable(),
});

/**
 * Type inference from Zod schemas
 * These types are guaranteed to match the validators
 */
export type ValidatedDbProfileRow = z.infer<typeof DbProfileRowSchema>;
export type ValidatedDbGoalRow = z.infer<typeof DbGoalRowSchema>;

/**
 * Helper functions for validation and conversion
 */

/**
 * Validates a profile row against the schema
 * Throws ZodError if validation fails
 */
export function validateDbProfileRow(data: unknown): ValidatedDbProfileRow {
  return DbProfileRowSchema.parse(data);
}

/**
 * Validates a goal row against the schema
 * Throws ZodError if validation fails
 */
export function validateDbGoalRow(data: unknown): ValidatedDbGoalRow {
  return DbGoalRowSchema.parse(data);
}

/**
 * Safe validation that returns null on error
 */
export function tryValidateDbProfileRow(data: unknown): ValidatedDbProfileRow | null {
  try {
    return DbProfileRowSchema.parse(data);
  } catch {
    return null;
  }
}

/**
 * Safe validation that returns null on error
 */
export function tryValidateDbGoalRow(data: unknown): ValidatedDbGoalRow | null {
  try {
    return DbGoalRowSchema.parse(data);
  } catch {
    return null;
  }
}

/**
 * Database query type helpers
 * Used with supabase.from<T>() for better typing
 */
export type DbProfileQueryResult = DbProfileRow | null;
export type DbProfileQueryResults = DbProfileRow[];
export type DbGoalQueryResult = DbGoalRow | null;
export type DbGoalQueryResults = DbGoalRow[];
