import { Goal } from '@/types/goals';

export const GOALS_DATABASE: Goal[] = [
  {
    id: 'surah-fatiha',
    nameEnglish: 'Surah Al-Fatiha',
    nameArabic: 'سورة الفاتحة',
    type: 'surah-xsmall',
    metadata: {
      versesCount: 7,
      pagesCount: 1,
      quartersCount: 1,
      surahCount: 1,
      defaultUnit: 'surah',
      difficulty: 'short',
      defaultPhaseSize: 3,
      supportsCustomPhaseSize: true,
    },
    units: [
      {
        id: 1,
        name: 'Al-Fatiha',
        arabicName: 'الفاتحة',
        versesCount: 7,
        startVerse: '1:1',
        endVerse: '1:7',
      },
    ],
    description: 'The Opening chapter of the Quran, the foundation of Islamic prayer',
  },
  {
    id: 'surah-bakarah',
    nameEnglish: 'Surah Al-Bakarah',
    nameArabic: 'سورة البقرة',
    type: 'surah-xlong',
    metadata: {
      versesCount: 286,
      pagesCount: 48,
      quartersCount: 20,
      surahCount: 1,
      defaultUnit: 'quarter',
      difficulty: 'long',
      defaultPhaseSize: 10,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 201, name: 'Quarter 1', arabicName: 'الربع الأول', versesCount: 25, startVerse: '2:1', endVerse: '2:25' },
      { id: 202, name: 'Quarter 2', arabicName: 'الربع الثاني', versesCount: 18, startVerse: '2:26', endVerse: '2:43' },
      { id: 203, name: 'Quarter 3', arabicName: 'الربع الثالث', versesCount: 16, startVerse: '2:44', endVerse: '2:59' },
      { id: 204, name: 'Quarter 4', arabicName: 'الربع الرابع', versesCount: 15, startVerse: '2:60', endVerse: '2:74' },
      { id: 205, name: 'Quarter 5', arabicName: 'الربع الخامس', versesCount: 17, startVerse: '2:75', endVerse: '2:91' },
      { id: 206, name: 'Quarter 6', arabicName: 'الربع السادس', versesCount: 14, startVerse: '2:92', endVerse: '2:105' },
      { id: 207, name: 'Quarter 7', arabicName: 'الربع السابع', versesCount: 18, startVerse: '2:106', endVerse: '2:123' },
      { id: 208, name: 'Quarter 8', arabicName: 'الربع الثامن', versesCount: 18, startVerse: '2:124', endVerse: '2:141' },
      { id: 209, name: 'Quarter 9', arabicName: 'الربع التاسع', versesCount: 16, startVerse: '2:142', endVerse: '2:157' },
      { id: 210, name: 'Quarter 10', arabicName: 'الربع العاشر', versesCount: 19, startVerse: '2:158', endVerse: '2:176' },
      { id: 211, name: 'Quarter 11', arabicName: 'الربع الحادي عشر', versesCount: 12, startVerse: '2:177', endVerse: '2:188' },
      { id: 212, name: 'Quarter 12', arabicName: 'الربع الثاني عشر', versesCount: 14, startVerse: '2:189', endVerse: '2:202' },
      { id: 213, name: 'Quarter 13', arabicName: 'الربع الثالث عشر', versesCount: 16, startVerse: '2:203', endVerse: '2:218' },
      { id: 214, name: 'Quarter 14', arabicName: 'الربع الرابع عشر', versesCount: 14, startVerse: '2:219', endVerse: '2:232' },
      { id: 215, name: 'Quarter 15', arabicName: 'الربع الخامس عشر', versesCount: 10, startVerse: '2:233', endVerse: '2:242' },
      { id: 216, name: 'Quarter 16', arabicName: 'الربع السادس عشر', versesCount: 10, startVerse: '2:243', endVerse: '2:252' },
      { id: 217, name: 'Quarter 17', arabicName: 'الربع السابع عشر', versesCount: 10, startVerse: '2:253', endVerse: '2:262' },
      { id: 218, name: 'Quarter 18', arabicName: 'الربع الثامن عشر', versesCount: 9, startVerse: '2:263', endVerse: '2:271' },
      { id: 219, name: 'Quarter 19', arabicName: 'الربع التاسع عشر', versesCount: 11, startVerse: '2:272', endVerse: '2:282' },
      { id: 220, name: 'Quarter 20', arabicName: 'الربع العشرون', versesCount: 4, startVerse: '2:283', endVerse: '2:286' },
    ],
    description: 'The Cow chapter, the longest Surah in the Quran with comprehensive guidance',
  },
  {
    id: 'surah-imran',
    nameEnglish: 'Surah Aal-e-Imran',
    nameArabic: 'سورة آل عمران',
    type: 'surah-xlong',
    metadata: {
      versesCount: 200,
      pagesCount: 28,
      quartersCount: 11,
      surahCount: 1,
      defaultUnit: 'quarter',
      difficulty: 'long',
      defaultPhaseSize: 10,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 301, name: 'Quarter 1', arabicName: 'الربع الأول', versesCount: 14, startVerse: '3:1', endVerse: '3:14' },
      { id: 302, name: 'Quarter 2', arabicName: 'الربع الثاني', versesCount: 18, startVerse: '3:15', endVerse: '3:32' },
      { id: 303, name: 'Quarter 3', arabicName: 'الربع الثالث', versesCount: 19, startVerse: '3:33', endVerse: '3:51' },
      { id: 304, name: 'Quarter 4', arabicName: 'الربع الرابع', versesCount: 23, startVerse: '3:52', endVerse: '3:74' },
      { id: 305, name: 'Quarter 5', arabicName: 'الربع الخامس', versesCount: 18, startVerse: '3:75', endVerse: '3:92' },
      { id: 306, name: 'Quarter 6', arabicName: 'الربع السادس', versesCount: 20, startVerse: '3:93', endVerse: '3:112' },
      { id: 307, name: 'Quarter 7', arabicName: 'الربع السابع', versesCount: 20, startVerse: '3:113', endVerse: '3:132' },
      { id: 308, name: 'Quarter 8', arabicName: 'الربع الثامن', versesCount: 20, startVerse: '3:133', endVerse: '3:152' },
      { id: 309, name: 'Quarter 9', arabicName: 'الربع التاسع', versesCount: 18, startVerse: '3:153', endVerse: '3:170' },
      { id: 310, name: 'Quarter 10', arabicName: 'الربع العاشر', versesCount: 15, startVerse: '3:171', endVerse: '3:185' },
      { id: 311, name: 'Quarter 11', arabicName: 'الربع الحادي عشر', versesCount: 15, startVerse: '3:186', endVerse: '3:200' },
    ],
    description: 'The Family of Imran, containing stories of the People of the Book',
  },
  {
    id: 'surah-kaaf',
    nameEnglish: 'Surah Al-Kaaf',
    nameArabic: 'سورة الكهف',
    type: 'surah-long',
    metadata: {
      versesCount: 110,
      pagesCount: 13,
      quartersCount: 8,
      surahCount: 1,
      defaultUnit: 'quarter',
      difficulty: 'long',
      defaultPhaseSize: 8,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 1801, name: 'Quarter 1', arabicName: 'الربع الأول', versesCount: 14, startVerse: '18:1', endVerse: '18:14' },
      { id: 1802, name: 'Quarter 2', arabicName: 'الربع الثاني', versesCount: 13, startVerse: '18:15', endVerse: '18:27' },
      { id: 1803, name: 'Quarter 3', arabicName: 'الربع الثالث', versesCount: 15, startVerse: '18:28', endVerse: '18:42' },
      { id: 1804, name: 'Quarter 4', arabicName: 'الربع الرابع', versesCount: 12, startVerse: '18:43', endVerse: '18:54' },
      { id: 1805, name: 'Quarter 5', arabicName: 'الربع الخامس', versesCount: 12, startVerse: '18:55', endVerse: '18:66' },
      { id: 1806, name: 'Quarter 6', arabicName: 'الربع السادس', versesCount: 14, startVerse: '18:67', endVerse: '18:80' },
      { id: 1807, name: 'Quarter 7', arabicName: 'الربع السابع', versesCount: 15, startVerse: '18:81', endVerse: '18:95' },
      { id: 1808, name: 'Quarter 8', arabicName: 'الربع الثامن', versesCount: 15, startVerse: '18:96', endVerse: '18:110' },
    ],
    description: 'The Cave chapter, containing the story of the People of the Cave',
  },
  {
    id: 'surah-rahman',
    nameEnglish: 'Surah Al-Rahman',
    nameArabic: 'سورة الرحمن',
    type: 'surah-small',
    metadata: {
      versesCount: 78,
      pagesCount: 2,
      quartersCount: 2,
      surahCount: 1,
      defaultUnit: 'page',
      difficulty: 'short',
      defaultPhaseSize: 8,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 5501, name: 'Page 1', arabicName: 'الصفحة الأولى', versesCount: 39, startVerse: '55:1', endVerse: '55:39' },
      { id: 5502, name: 'Page 2', arabicName: 'الصفحة الثانية', versesCount: 39, startVerse: '55:40', endVerse: '55:78' },
    ],
    description: 'The Most Merciful, highlighting the blessings and mercy of Allah',
  },
  {
    id: 'surah-waqiah',
    nameEnglish: 'Surah Al-Waqiah',
    nameArabic: 'سورة الواقعة',
    type: 'surah-small',
    metadata: {
      versesCount: 96,
      pagesCount: 2,
      quartersCount: 3,
      surahCount: 1,
      defaultUnit: 'page',
      difficulty: 'short',
      defaultPhaseSize: 10,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 5601, name: 'Page 1', arabicName: 'الصفحة الأولى', versesCount: 48, startVerse: '56:1', endVerse: '56:48' },
      { id: 5602, name: 'Page 2', arabicName: 'الصفحة الثانية', versesCount: 48, startVerse: '56:49', endVerse: '56:96' },
    ],
    description: 'The Inevitable Event, describing the Day of Judgment',
  },
  {
    id: 'short-surahs',
    nameEnglish: 'Short Surahs',
    nameArabic: 'السور القصيرة',
    type: 'group',
    metadata: {
      versesCount: 48,
      pagesCount: 10,
      quartersCount: 4,
      surahCount: 9,
      defaultUnit: 'surah',
      difficulty: 'short',
      defaultPhaseSize: 5,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 103, name: 'Al-Asr', arabicName: 'العصر', versesCount: 3, startVerse: '103:1', endVerse: '103:3' },
      { id: 105, name: 'Al-Fil', arabicName: 'الفيل', versesCount: 5, startVerse: '105:1', endVerse: '105:5' },
      { id: 106, name: 'Quraish', arabicName: 'قريش', versesCount: 4, startVerse: '106:1', endVerse: '106:4' },
      { id: 107, name: 'Al-Ma\'un', arabicName: 'الماعون', versesCount: 7, startVerse: '107:1', endVerse: '107:7' },
      { id: 110, name: 'An-Nasr', arabicName: 'النصر', versesCount: 3, startVerse: '110:1', endVerse: '110:3' },
      { id: 111, name: 'Al-Masad', arabicName: 'المسد', versesCount: 5, startVerse: '111:1', endVerse: '111:5' },
      { id: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', versesCount: 4, startVerse: '112:1', endVerse: '112:4' },
      { id: 113, name: 'Al-Falaq', arabicName: 'الفلق', versesCount: 5, startVerse: '113:1', endVerse: '113:5' },
      { id: 114, name: 'An-Nas', arabicName: 'الناس', versesCount: 6, startVerse: '114:1', endVerse: '114:6' },
    ],
    description: 'A collection of 9 short Surahs, perfect for beginners and memorization',
  },
  {
    id: 'juz-30',
    nameEnglish: "Juz' 30",
    nameArabic: "جزء عم",
    type: 'juz',
    metadata: {
      versesCount: 564,
      pagesCount: 21,
      quartersCount: 8,
      surahCount: 37,
      defaultUnit: 'surah',
      difficulty: 'short',
      defaultPhaseSize: 8,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 78, name: "An-Naba", arabicName: "النبأ", versesCount: 40, startVerse: '78:1', endVerse: '78:40' },
      { id: 79, name: "An-Nazi'at", arabicName: "النازعات", versesCount: 46, startVerse: '79:1', endVerse: '79:46' },
      { id: 80, name: "Abasa", arabicName: "عبس", versesCount: 42, startVerse: '80:1', endVerse: '80:42' },
      { id: 81, name: "At-Takwir", arabicName: "التكوير", versesCount: 29, startVerse: '81:1', endVerse: '81:29' },
      { id: 82, name: "Al-Infitar", arabicName: "الإنفطار", versesCount: 19, startVerse: '82:1', endVerse: '82:19' },
      { id: 83, name: "Al-Mutaffifin", arabicName: "المطففين", versesCount: 36, startVerse: '83:1', endVerse: '83:36' },
      { id: 84, name: "Al-Inshiqaq", arabicName: "الإنشقاق", versesCount: 25, startVerse: '84:1', endVerse: '84:25' },
      { id: 85, name: "Al-Buruj", arabicName: "البروج", versesCount: 22, startVerse: '85:1', endVerse: '85:22' },
      { id: 86, name: "At-Tariq", arabicName: "الطارق", versesCount: 17, startVerse: '86:1', endVerse: '86:17' },
      { id: 87, name: "Al-A'la", arabicName: "الأعلى", versesCount: 19, startVerse: '87:1', endVerse: '87:19' },
      { id: 88, name: "Al-Ghashiyah", arabicName: "الغاشية", versesCount: 26, startVerse: '88:1', endVerse: '88:26' },
      { id: 89, name: "Al-Fajr", arabicName: "الفجر", versesCount: 30, startVerse: '89:1', endVerse: '89:30' },
      { id: 90, name: "Al-Balad", arabicName: "البلد", versesCount: 20, startVerse: '90:1', endVerse: '90:20' },
      { id: 91, name: "Ash-Shams", arabicName: "الشمس", versesCount: 15, startVerse: '91:1', endVerse: '91:15' },
      { id: 92, name: "Al-Lail", arabicName: "الليل", versesCount: 21, startVerse: '92:1', endVerse: '92:21' },
      { id: 93, name: "Ad-Duha", arabicName: "الضحى", versesCount: 11, startVerse: '93:1', endVerse: '93:11' },
      { id: 94, name: "Ash-Sharh", arabicName: "الشرح", versesCount: 8, startVerse: '94:1', endVerse: '94:8' },
      { id: 95, name: "At-Tin", arabicName: "التين", versesCount: 8, startVerse: '95:1', endVerse: '95:8' },
      { id: 96, name: "Al-Alaq", arabicName: "العلق", versesCount: 19, startVerse: '96:1', endVerse: '96:19' },
      { id: 97, name: "Al-Qadr", arabicName: "القدر", versesCount: 5, startVerse: '97:1', endVerse: '97:5' },
      { id: 98, name: "Al-Bayyinah", arabicName: "البينة", versesCount: 8, startVerse: '98:1', endVerse: '98:8' },
      { id: 99, name: "Az-Zalzalah", arabicName: "الزلزلة", versesCount: 8, startVerse: '99:1', endVerse: '99:8' },
      { id: 100, name: "Al-Adiyat", arabicName: "العاديات", versesCount: 11, startVerse: '100:1', endVerse: '100:11' },
      { id: 101, name: "Al-Qari'ah", arabicName: "القارعة", versesCount: 11, startVerse: '101:1', endVerse: '101:11' },
      { id: 102, name: "At-Takathur", arabicName: "التكاثر", versesCount: 8, startVerse: '102:1', endVerse: '102:8' },
      { id: 103, name: "Al-Asr", arabicName: "العصر", versesCount: 3, startVerse: '103:1', endVerse: '103:3' },
      { id: 104, name: "Al-Humazah", arabicName: "الهمزة", versesCount: 9, startVerse: '104:1', endVerse: '104:9' },
      { id: 105, name: "Al-Fil", arabicName: "الفيل", versesCount: 5, startVerse: '105:1', endVerse: '105:5' },
      { id: 106, name: "Quraish", arabicName: "قريش", versesCount: 4, startVerse: '106:1', endVerse: '106:4' },
      { id: 107, name: "Al-Ma'un", arabicName: "الماعون", versesCount: 7, startVerse: '107:1', endVerse: '107:7' },
      { id: 108, name: "Al-Kawthar", arabicName: "الكوثر", versesCount: 3, startVerse: '108:1', endVerse: '108:3' },
      { id: 109, name: "Al-Kafirun", arabicName: "الكافرون", versesCount: 6, startVerse: '109:1', endVerse: '109:6' },
      { id: 110, name: "An-Nasr", arabicName: "النصر", versesCount: 3, startVerse: '110:1', endVerse: '110:3' },
      { id: 111, name: "Al-Masad", arabicName: "المسد", versesCount: 5, startVerse: '111:1', endVerse: '111:5' },
      { id: 112, name: "Al-Ikhlas", arabicName: "الإخلاص", versesCount: 4, startVerse: '112:1', endVerse: '112:4' },
      { id: 113, name: "Al-Falaq", arabicName: "الفلق", versesCount: 5, startVerse: '113:1', endVerse: '113:5' },
      { id: 114, name: "An-Nas", arabicName: "الناس", versesCount: 6, startVerse: '114:1', endVerse: '114:6' },
    ],
    description: 'Learn the last Juz of the Quran with 37 short Surahs',
  },
  {
    id: 'juz-29',
    nameEnglish: "Juz' 29",
    nameArabic: "جزء تبارك",
    type: 'juz',
    metadata: {
      versesCount: 447,
      pagesCount: 20,
      quartersCount: 8,
      surahCount: 11,
      defaultUnit: 'surah',
      difficulty: 'medium',
      defaultPhaseSize: 10,
      supportsCustomPhaseSize: true,
    },
    units: [
      { id: 67, name: "Al-Mulk", arabicName: "الملك", versesCount: 30, startVerse: '67:1', endVerse: '67:30' },
      { id: 68, name: "Al-Qalam", arabicName: "القلم", versesCount: 52, startVerse: '68:1', endVerse: '68:52' },
      { id: 69, name: "Al-Haqqah", arabicName: "الحاقة", versesCount: 52, startVerse: '69:1', endVerse: '69:52' },
      { id: 70, name: "Al-Ma'arij", arabicName: "المعارج", versesCount: 44, startVerse: '70:1', endVerse: '70:44' },
      { id: 71, name: "Nuh", arabicName: "نوح", versesCount: 28, startVerse: '71:1', endVerse: '71:28' },
      { id: 72, name: "Al-Jinn", arabicName: "الجن", versesCount: 28, startVerse: '72:1', endVerse: '72:28' },
      { id: 73, name: "Al-Muzzammil", arabicName: "المزمل", versesCount: 20, startVerse: '73:1', endVerse: '73:20' },
      { id: 74, name: "Al-Muddathir", arabicName: "المدثر", versesCount: 56, startVerse: '74:1', endVerse: '74:56' },
      { id: 75, name: "Al-Qiyamah", arabicName: "القيامة", versesCount: 40, startVerse: '75:1', endVerse: '75:40' },
      { id: 76, name: "Al-Insan", arabicName: "الإنسان", versesCount: 31, startVerse: '76:1', endVerse: '76:31' },
      { id: 77, name: "Al-Mursalat", arabicName: "المرسلات", versesCount: 50, startVerse: '77:1', endVerse: '77:50' },
    ],
    description: 'Master the blessed Juz with 11 Surahs of varying lengths',
  },
];

export function getGoalById(id: string): Goal | undefined {
  return GOALS_DATABASE.find(goal => goal.id === id);
}

export function getAllGoals(): Goal[] {
  return GOALS_DATABASE;
}
