import { Goal } from '@/types/goals';

export const GOALS_DATABASE: Goal[] = [
  {
    id: 'surah-fatiha',
    nameEnglish: 'Surah Al-Fatiha',
    nameArabic: 'سورة الفاتحة',
    type: 'surah-xsmall',
    metadata: {
      versesCount: 7,
      pagesCount: 1,
      quartersCount: 1,
      surahCount: 1,
      defaultUnit: 'surah',
      difficulty: 'short',
    },
    units: [
      { id: 1, name: 'Al-Fatiha', arabicName: 'الفاتحة' },
    ],
    description: 'The Opening chapter of the Quran, the foundation of Islamic prayer',
  },
  {
    id: 'surah-bakarah',
    nameEnglish: 'Surah Al-Bakarah',
    nameArabic: 'سورة البقرة',
    type: 'surah-xlong',
    metadata: {
      versesCount: 286,
      pagesCount: 48,
      quartersCount: 20,
      surahCount: 1,
      defaultUnit: 'quarter',
      difficulty: 'long',
    },
    units: [
      { id: 201, name: 'Quarter 1', arabicName: 'الربع الأول' },
      { id: 202, name: 'Quarter 2', arabicName: 'الربع الثاني' },
      { id: 203, name: 'Quarter 3', arabicName: 'الربع الثالث' },
      { id: 204, name: 'Quarter 4', arabicName: 'الربع الرابع' },
      { id: 205, name: 'Quarter 5', arabicName: 'الربع الخامس' },
      { id: 206, name: 'Quarter 6', arabicName: 'الربع السادس' },
      { id: 207, name: 'Quarter 7', arabicName: 'الربع السابع' },
      { id: 208, name: 'Quarter 8', arabicName: 'الربع الثامن' },
      { id: 209, name: 'Quarter 9', arabicName: 'الربع التاسع' },
      { id: 210, name: 'Quarter 10', arabicName: 'الربع العاشر' },
      { id: 211, name: 'Quarter 11', arabicName: 'الربع الحادي عشر' },
      { id: 212, name: 'Quarter 12', arabicName: 'الربع الثاني عشر' },
      { id: 213, name: 'Quarter 13', arabicName: 'الربع الثالث عشر' },
      { id: 214, name: 'Quarter 14', arabicName: 'الربع الرابع عشر' },
      { id: 215, name: 'Quarter 15', arabicName: 'الربع الخامس عشر' },
      { id: 216, name: 'Quarter 16', arabicName: 'الربع السادس عشر' },
      { id: 217, name: 'Quarter 17', arabicName: 'الربع السابع عشر' },
      { id: 218, name: 'Quarter 18', arabicName: 'الربع الثامن عشر' },
      { id: 219, name: 'Quarter 19', arabicName: 'الربع التاسع عشر' },
      { id: 220, name: 'Quarter 20', arabicName: 'الربع العشرون' },
    ],
    description: 'The Cow chapter, the longest Surah in the Quran with comprehensive guidance',
  },
  {
    id: 'surah-imran',
    nameEnglish: 'Surah Aal-e-Imran',
    nameArabic: 'سورة آل عمران',
    type: 'surah-long',
    metadata: {
      versesCount: 200,
      pagesCount: 28,
      quartersCount: 8,
      surahCount: 1,
      defaultUnit: 'quarter',
      difficulty: 'long',
    },
    units: [
      { id: 301, name: 'Quarter 1', arabicName: 'الربع الأول' },
      { id: 302, name: 'Quarter 2', arabicName: 'الربع الثاني' },
      { id: 303, name: 'Quarter 3', arabicName: 'الربع الثالث' },
      { id: 304, name: 'Quarter 4', arabicName: 'الربع الرابع' },
      { id: 305, name: 'Quarter 5', arabicName: 'الربع الخامس' },
      { id: 306, name: 'Quarter 6', arabicName: 'الربع السادس' },
      { id: 307, name: 'Quarter 7', arabicName: 'الربع السابع' },
      { id: 308, name: 'Quarter 8', arabicName: 'الربع الثامن' },
    ],
    description: 'The Family of Imran, containing stories of the People of the Book',
  },
  {
    id: 'surah-kaaf',
    nameEnglish: 'Surah Al-Kaaf',
    nameArabic: 'سورة الكهف',
    type: 'surah-medium',
    metadata: {
      versesCount: 110,
      pagesCount: 13,
      quartersCount: 8,
      surahCount: 1,
      defaultUnit: 'quarter',
      difficulty: 'medium',
    },
    units: [
      { id: 1801, name: 'Quarter 1', arabicName: 'الربع الأول' },
      { id: 1802, name: 'Quarter 2', arabicName: 'الربع الثاني' },
      { id: 1803, name: 'Quarter 3', arabicName: 'الربع الثالث' },
      { id: 1804, name: 'Quarter 4', arabicName: 'الربع الرابع' },
      { id: 1805, name: 'Quarter 5', arabicName: 'الربع الخامس' },
      { id: 1806, name: 'Quarter 6', arabicName: 'الربع السادس' },
      { id: 1807, name: 'Quarter 7', arabicName: 'الربع السابع' },
      { id: 1808, name: 'Quarter 8', arabicName: 'الربع الثامن' },
    ],
    description: 'The Cave chapter, containing the story of the People of the Cave',
  },
  {
    id: 'surah-rahman',
    nameEnglish: 'Surah Al-Rahman',
    nameArabic: 'سورة الرحمن',
    type: 'surah-small',
    metadata: {
      versesCount: 78,
      pagesCount: 2,
      quartersCount: 2,
      surahCount: 1,
      defaultUnit: 'page',
      difficulty: 'short',
    },
    units: [
      { id: 5501, name: 'Page 1', arabicName: 'الصفحة الأولى' },
      { id: 5502, name: 'Page 2', arabicName: 'الصفحة الثانية' },
    ],
    description: 'The Most Merciful, highlighting the blessings and mercy of Allah',
  },
  {
    id: 'surah-waqiah',
    nameEnglish: 'Surah Al-Waqiah',
    nameArabic: 'سورة الواقعة',
    type: 'surah-small',
    metadata: {
      versesCount: 96,
      pagesCount: 2,
      quartersCount: 3,
      surahCount: 1,
      defaultUnit: 'page',
      difficulty: 'short',
    },
    units: [
      { id: 5601, name: 'Page 1', arabicName: 'الصفحة الأولى' },
      { id: 5602, name: 'Page 2', arabicName: 'الصفحة الثانية' },
    ],
    description: 'The Inevitable Event, describing the Day of Judgment',
  },
  {
    id: 'short-surahs',
    nameEnglish: 'Short Surahs',
    nameArabic: 'السور القصيرة',
    type: 'group',
    metadata: {
      versesCount: 48,
      pagesCount: 10,
      quartersCount: 4,
      surahCount: 9,
      defaultUnit: 'surah',
      difficulty: 'short',
    },
    units: [
      { id: 103, name: 'Al-Asr', arabicName: 'العصر' },
      { id: 105, name: 'Al-Fil', arabicName: 'الفيل' },
      { id: 106, name: 'Quraish', arabicName: 'قريش' },
      { id: 107, name: 'Al-Ma\'un', arabicName: 'الماعون' },
      { id: 110, name: 'An-Nasr', arabicName: 'النصر' },
      { id: 111, name: 'Al-Masad', arabicName: 'المسد' },
      { id: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص' },
      { id: 113, name: 'Al-Falaq', arabicName: 'الفلق' },
      { id: 114, name: 'An-Nas', arabicName: 'الناس' },
    ],
    description: 'A collection of 9 short Surahs, perfect for beginners and memorization',
  },
  {
    id: 'juz-30',
    nameEnglish: "Juz' 30",
    nameArabic: "جزء عم",
    type: 'juz',
    metadata: {
      versesCount: 564,
      pagesCount: 21,
      quartersCount: 8,
      surahCount: 37,
      defaultUnit: 'surah',
      difficulty: 'Easy',
    },
    units: [
      { id: 78, name: "An-Naba", arabicName: "النبأ" },
      { id: 79, name: "An-Nazi'at", arabicName: "النازعات" },
      { id: 80, name: "Abasa", arabicName: "عبس" },
      { id: 81, name: "At-Takwir", arabicName: "التكوير" },
      { id: 82, name: "Al-Infitar", arabicName: "الإنفطار" },
      { id: 83, name: "Al-Mutaffifin", arabicName: "المطففين" },
      { id: 84, name: "Al-Inshiqaq", arabicName: "الإنشقاق" },
      { id: 85, name: "Al-Buruj", arabicName: "البروج" },
      { id: 86, name: "At-Tariq", arabicName: "الطارق" },
      { id: 87, name: "Al-A'la", arabicName: "الأعلى" },
      { id: 88, name: "Al-Ghashiyah", arabicName: "الغاشية" },
      { id: 89, name: "Al-Fajr", arabicName: "الفجر" },
      { id: 90, name: "Al-Balad", arabicName: "البلد" },
      { id: 91, name: "Ash-Shams", arabicName: "الشمس" },
      { id: 92, name: "Al-Lail", arabicName: "الليل" },
      { id: 93, name: "Ad-Duha", arabicName: "الضحى" },
      { id: 94, name: "Ash-Sharh", arabicName: "الشرح" },
      { id: 95, name: "At-Tin", arabicName: "التين" },
      { id: 96, name: "Al-Alaq", arabicName: "العلق" },
      { id: 97, name: "Al-Qadr", arabicName: "القدر" },
      { id: 98, name: "Al-Bayyinah", arabicName: "البينة" },
      { id: 99, name: "Az-Zalzalah", arabicName: "الزلزلة" },
      { id: 100, name: "Al-Adiyat", arabicName: "العاديات" },
      { id: 101, name: "Al-Qari'ah", arabicName: "القارعة" },
      { id: 102, name: "At-Takathur", arabicName: "التكاثر" },
      { id: 103, name: "Al-Asr", arabicName: "العصر" },
      { id: 104, name: "Al-Humazah", arabicName: "الهمزة" },
      { id: 105, name: "Al-Fil", arabicName: "الفيل" },
      { id: 106, name: "Quraish", arabicName: "قريش" },
      { id: 107, name: "Al-Ma'un", arabicName: "الماعون" },
      { id: 108, name: "Al-Kawthar", arabicName: "الكوثر" },
      { id: 109, name: "Al-Kafirun", arabicName: "الكافرون" },
      { id: 110, name: "An-Nasr", arabicName: "النصر" },
      { id: 111, name: "Al-Masad", arabicName: "المسد" },
      { id: 112, name: "Al-Ikhlas", arabicName: "الإخلاص" },
      { id: 113, name: "Al-Falaq", arabicName: "الفلق" },
      { id: 114, name: "An-Nas", arabicName: "الناس" },
    ],
    description: 'Learn the last Juz of the Quran with 37 short Surahs',
  },
  {
    id: 'juz-29',
    nameEnglish: "Juz' 29",
    nameArabic: "جزء تبارك",
    type: 'juz',
    metadata: {
      versesCount: 447,
      pagesCount: 20,
      quartersCount: 8,
      surahCount: 11,
      defaultUnit: 'surah',
      difficulty: 'medium',
    },
    units: [
      { id: 67, name: "Al-Mulk", arabicName: "الملك" },
      { id: 68, name: "Al-Qalam", arabicName: "القلم" },
      { id: 69, name: "Al-Haqqah", arabicName: "الحاقة" },
      { id: 70, name: "Al-Ma'arij", arabicName: "المعارج" },
      { id: 71, name: "Nuh", arabicName: "نوح" },
      { id: 72, name: "Al-Jinn", arabicName: "الجن" },
      { id: 73, name: "Al-Muzzammil", arabicName: "المزمل" },
      { id: 74, name: "Al-Muddathir", arabicName: "المد��ر" },
      { id: 75, name: "Al-Qiyamah", arabicName: "القيامة" },
      { id: 76, name: "Al-Insan", arabicName: "الإنسان" },
      { id: 77, name: "Al-Mursalat", arabicName: "المرسلات" },
    ],
    description: 'Master the blessed Juz with 11 Surahs of varying lengths',
  },
];

export function getGoalById(id: string): Goal | undefined {
  return GOALS_DATABASE.find(goal => goal.id === id);
}

export function getAllGoals(): Goal[] {
  return GOALS_DATABASE;
}
